### ISSUE TITLE
Support for Raspberry Pi Zero 1.3

### ISSUE THREAD

**Issue by robster7674** [MrMLynch/piratepaperwallet#5]
Please provide a release for the Raspberry Pi Zero 1.3, as this is one of the few true airgapped options out there. Architecture is armv6l.
Information and specs: https://www.raspberrypi.org/products/raspberry-pi-zero/.

**Comment by nemo58** [comment]
Cross-compiling information for anyone interested in doing it themselves, https://stackoverflow.com/questions/19162072/how-to-install-the-raspberry-pi-cross-compiler-on-my-linux-host-machine

**Comment by robster7674** [comment]
Thanks for the link @nemo58. I compiled arm 32-bit yesterday, but still it would be nice to have an official release.
[piratepaperwallet.zip](https://github.com/MrMLynch/piratepaperwallet/files/6370423/piratepaperwallet.zip)
